version: '2'
services:
  db:
    image: postgres
    environment:
      # Define our database password, following the image documentation
      POSTGRES_PASSWORD: '123456A!'
    # Create a named volume to store persistent data, without the inital dot
    volumes:
      - data-postgres:/var/lib/postgresql/data

  web:
    build: ./web
    # Avoid race condition by sleeping a while, not the best practice tough
    command: bash -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - "./deployeveryday:/code"
    expose:
      - "8000"
    depends_on:
      - db
      - nginx
    environment:
      VIRTUAL_HOST: 'localhost'

  nginx:
    image: jwilder/nginx-proxy
    # Expose socket to nginx-proxy
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    ports:
      - "80:80"


# Need to describe named volumes, weird, I know
volumes:
  data-postgres:
